"""initial migration

Revision ID: cd2c639542a1
Revises: 
Create Date: 2025-10-25 10:59:58.115940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd2c639542a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotes',
    sa.Column('lote_code', sa.String(length=55), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lotes_lote_code'), 'lotes', ['lote_code'], unique=True)
    op.create_table('products',
    sa.Column('product_code', sa.String(length=55), nullable=False),
    sa.Column('product_name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_product_code'), 'products', ['product_code'], unique=False)
    op.create_table('assignments',
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('flight_assigned', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('draft', 'ready', 'loaded', 'rejected', name='assignmentstatus'), server_default='draft', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_flight_assigned'), 'assignments', ['flight_assigned'], unique=False)
    op.create_index(op.f('ix_assignments_lot_id'), 'assignments', ['lot_id'], unique=False)
    op.create_index(op.f('ix_assignments_status'), 'assignments', ['status'], unique=False)
    op.create_table('lote_products',
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('certification_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lotes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lote_products_lot_id'), 'lote_products', ['lot_id'], unique=False)
    op.create_index(op.f('ix_lote_products_product_id'), 'lote_products', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lote_products_product_id'), table_name='lote_products')
    op.drop_index(op.f('ix_lote_products_lot_id'), table_name='lote_products')
    op.drop_table('lote_products')
    op.drop_index(op.f('ix_assignments_status'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_lot_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_flight_assigned'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_products_product_code'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_lotes_lote_code'), table_name='lotes')
    op.drop_table('lotes')
    # ### end Alembic commands ###
